// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAStClsp8Zr3M3E9LMaNyvLx9GNaZMcZA',
    appId: '1:986993556082:web:1cadbc680e751b244aa0eb',
    messagingSenderId: '986993556082',
    projectId: 'fashion-app-1d9db',
    authDomain: 'fashion-app-1d9db.firebaseapp.com',
    storageBucket: 'fashion-app-1d9db.firebasestorage.app',
    measurementId: 'G-FWC6KT3QFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSkCgsP-ddDqCcpjtoO7b3S4cZl_Lhdg',
    appId: '1:986993556082:android:a720f104a561218f4aa0eb',
    messagingSenderId: '986993556082',
    projectId: 'fashion-app-1d9db',
    storageBucket: 'fashion-app-1d9db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJy3utyv59oHhX4N0pIURYEup07-yYjfs',
    appId: '1:986993556082:ios:bb2e3c180f2543484aa0eb',
    messagingSenderId: '986993556082',
    projectId: 'fashion-app-1d9db',
    storageBucket: 'fashion-app-1d9db.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );
}
